(package "org-pretty-table"
         "1.0.0"
         "Replace org-table characters with box-drawing unicode glyphs")

(website-url "https://github.com/Fuco1/org-pretty-table")
(keywords "faces")

(package-file "org-pretty-table.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "org" "9")
(depends-on "emacs" "24.1")

(development
 (depends-on "elsa")
 (depends-on "undercover")
 (depends-on "buttercup"))
